name: Variables Devops

on: [push,workflow_dispatch]

env:
    PROYECTO: "Mi app DevOps"
    AMBIENTE: "Desarrollo"

jobs:
    mostrar:
        runs-on: ubuntu-latest
        env:
            RESPONSABLE: "Estudiante Devopss"
        steps:
            - name: Mostrar info
              run: |
                        echo "Proyecto: $PROYECTO"
                        echo "Ambiente: $AMBIENTE"
                        echo "Responsable: $RESPONSABLE"